export enum EventName {
  chatGlobalMessage = 'globalChatMessage',
  messageToServer = 'messageToServer',
  joinRoomRequest = 'joinRoom',
  leaveRoomRequest = 'leaveRoom',
  getRoomList = 'getRoomList',
  createLobbyRequest = 'createLobbyRequest',
  isUuidUniqueRequest = 'isUuidUniqueRequest',
  joinLobbyRequest = 'joinLobbyRequest',
  destroyLobbyRequest = 'destroyLobbyRequest',
  getLobbyData = 'getLobbyData',
  getLobbyList = 'getLobbyList',
  lobbyCreated = 'lobbyCreated',
  isPasswordCorrectRequest = 'isPasswordCorrectRequest',
  joinGlobalChat = 'joinGlobalChat',
  isLobbyNameUniqueRequest = 'isLobbyNameUniqueRequest',
  joinLobby = 'joinLobby',
  leaveLobby = 'leaveLobby',
  leaveLobbyRequest = "leaveLobbyRequest",
  getRandomMemes = "getRandomMemes"
}